@CodexTest_HostAddress = http://localhost:5073

GET {{CodexTest_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{CodexTest_HostAddress}}/weatherforecast
Content-Type: application/json

{
  "date": "2030-01-01",
  "temperatureC": 25,
  "summary": "Warm"
}

###

PATCH {{CodexTest_HostAddress}}/weatherforecast/1
Content-Type: application/json-patch+json

[
  { "op": "replace", "path": "/summary", "value": "Hot" }
]

###

DELETE {{CodexTest_HostAddress}}/weatherforecast/1

###
